#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <overlay_framework/overlay.hpp>
#include <overlay_framework/color.hpp>
#include <overlay_framework/math.hpp>

using namespace overlay_framework;
using namespace overlay_framework::math;

// trig
//

TEST_CASE("Trigonometry calculations", "[math]") {
    REQUIRE_THAT(deg_to_rad(0.f), Catch::Matchers::WithinAbs(0, 0.0001));
    REQUIRE_THAT(deg_to_rad(45.f), Catch::Matchers::WithinAbs(0.785398, 0.0001));
    REQUIRE_THAT(deg_to_rad(-45.f), Catch::Matchers::WithinAbs(-0.785398, 0.0001));
    REQUIRE_THAT(deg_to_rad(90.f), Catch::Matchers::WithinAbs(1.5708, 0.0001));
    REQUIRE_THAT(deg_to_rad(-90.f), Catch::Matchers::WithinAbs(-1.5708, 0.0001));
    REQUIRE_THAT(deg_to_rad(180.f), Catch::Matchers::WithinAbs(3.14159, 0.0001));
    REQUIRE_THAT(deg_to_rad(-180.f), Catch::Matchers::WithinAbs(-3.14159, 0.0001));
    REQUIRE_THAT(deg_to_rad(225.f), Catch::Matchers::WithinAbs(3.92699, 0.0001));
    REQUIRE_THAT(deg_to_rad(270.f), Catch::Matchers::WithinAbs(4.71239, 0.0001));
    REQUIRE_THAT(deg_to_rad(360.f), Catch::Matchers::WithinAbs(6.28319, 0.0001));
    REQUIRE_THAT(deg_to_rad(-360.f), Catch::Matchers::WithinAbs(-6.28319, 0.0001));
}

//
// I'm sorry, but the code below was generated by Claude.
// However I tried to manually check at least *some* of it...
//

// color_t
//

TEST_CASE("color_t constructor", "[color_t]") {
    SECTION("RGB constructor with default alpha") {
        color_t color(255, 128, 64);
        REQUIRE(color.r == 255);
        REQUIRE(color.g == 128);
        REQUIRE(color.b == 64);
        REQUIRE(color.a == 255);
    }

    SECTION("RGBA constructor") {
        color_t color(100, 150, 200, 180);
        REQUIRE(color.r == 100);
        REQUIRE(color.g == 150);
        REQUIRE(color.b == 200);
        REQUIRE(color.a == 180);
    }

    SECTION("Edge values") {
        color_t black(0, 0, 0, 0);
        REQUIRE(black.r == 0);
        REQUIRE(black.g == 0);
        REQUIRE(black.b == 0);
        REQUIRE(black.a == 0);

        color_t white(255, 255, 255, 255);
        REQUIRE(white.r == 255);
        REQUIRE(white.g == 255);
        REQUIRE(white.b == 255);
        REQUIRE(white.a == 255);
    }
}

TEST_CASE("color_t from_hex", "[color_t][from_hex]") {
    SECTION("Full opacity colors") {
        auto red = color_t::from_hex(0xFF0000FF);
        REQUIRE(red.r == 255);
        REQUIRE(red.g == 0);
        REQUIRE(red.b == 0);
        REQUIRE(red.a == 255);

        auto green = color_t::from_hex(0x00FF00FF);
        REQUIRE(green.r == 0);
        REQUIRE(green.g == 255);
        REQUIRE(green.b == 0);
        REQUIRE(green.a == 255);

        auto blue = color_t::from_hex(0x0000FFFF);
        REQUIRE(blue.r == 0);
        REQUIRE(blue.g == 0);
        REQUIRE(blue.b == 255);
        REQUIRE(blue.a == 255);
    }

    SECTION("Transparent colors") {
        auto transparent_red = color_t::from_hex(0xFF000080);
        REQUIRE(transparent_red.r == 255);
        REQUIRE(transparent_red.g == 0);
        REQUIRE(transparent_red.b == 0);
        REQUIRE(transparent_red.a == 128);

        auto fully_transparent = color_t::from_hex(0xFFFFFF00);
        REQUIRE(fully_transparent.r == 255);
        REQUIRE(fully_transparent.g == 255);
        REQUIRE(fully_transparent.b == 255);
        REQUIRE(fully_transparent.a == 0);
    }

    SECTION("Mixed values") {
        auto color = color_t::from_hex(0x8040C0A0);
        REQUIRE(color.r == 128);
        REQUIRE(color.g == 64);
        REQUIRE(color.b == 192);
        REQUIRE(color.a == 160);
    }

    SECTION("Edge cases") {
        auto black = color_t::from_hex(0x00000000);
        REQUIRE(black.r == 0);
        REQUIRE(black.g == 0);
        REQUIRE(black.b == 0);
        REQUIRE(black.a == 0);

        auto max_color = color_t::from_hex(0xFFFFFFFF);
        REQUIRE(max_color.r == 255);
        REQUIRE(max_color.g == 255);
        REQUIRE(max_color.b == 255);
        REQUIRE(max_color.a == 255);
    }
}

TEST_CASE("color_t to_hex", "[color_t][to_hex]") {
    SECTION("Primary colors") {
        color_t red(255, 0, 0, 255);
        REQUIRE(red.to_hex() == 0xFF0000FF);

        color_t green(0, 255, 0, 255);
        REQUIRE(green.to_hex() == 0x00FF00FF);

        color_t blue(0, 0, 255, 255);
        REQUIRE(blue.to_hex() == 0x0000FFFF);
    }

    SECTION("Transparent colors") {
        color_t transparent_red(255, 0, 0, 128);
        REQUIRE(transparent_red.to_hex() == 0xFF000080);

        color_t fully_transparent(255, 255, 255, 0);
        REQUIRE(fully_transparent.to_hex() == 0xFFFFFF00);
    }

    SECTION("Mixed values") {
        color_t color(128, 64, 192, 160);
        REQUIRE(color.to_hex() == 0x8040C0A0);
    }

    SECTION("Edge cases") {
        color_t black(0, 0, 0, 0);
        REQUIRE(black.to_hex() == 0x00000000);

        color_t white(255, 255, 255, 255);
        REQUIRE(white.to_hex() == 0xFFFFFFFF);
    }
}

TEST_CASE("color_t hex roundtrip", "[color_t][roundtrip]") {
    SECTION("from_hex -> to_hex roundtrip") {
        std::vector<uint32_t> test_values = { 0x00000000, 0xFFFFFFFF, 0xFF0000FF, 0x00FF00FF, 0x0000FFFF,
                                              0x80804080, 0x12345678, 0xABCDEF99, 0x7F7F7F7F };

        for (uint32_t hex : test_values) {
            auto color = color_t::from_hex(hex);
            REQUIRE(color.to_hex() == hex);
        }
    }

    SECTION("constructor -> to_hex -> from_hex roundtrip") {
        std::vector<std::tuple<uint8_t, uint8_t, uint8_t, uint8_t>> test_colors = {
            { 0, 0, 0, 0 },     { 255, 255, 255, 255 }, { 255, 0, 0, 255 },    { 0, 255, 0, 255 },
            { 0, 0, 255, 255 }, { 128, 64, 192, 160 },  { 100, 150, 200, 50 }, { 33, 66, 99, 132 }
        };

        for (auto [r, g, b, a] : test_colors) {
            color_t original(r, g, b, a);
            uint32_t hex = original.to_hex();
            color_t reconstructed = color_t::from_hex(hex);

            REQUIRE(reconstructed.r == original.r);
            REQUIRE(reconstructed.g == original.g);
            REQUIRE(reconstructed.b == original.b);
            REQUIRE(reconstructed.a == original.a);
        }
    }
}

TEST_CASE("color_t to_direct2d", "[color_t][to_direct2d]") {
    SECTION("Basic color conversion") {
        color_t red(255, 0, 0, 255);
        auto d2d_red = red.to_direct2d();
        REQUIRE_THAT(d2d_red.r, Catch::Matchers::WithinAbs(1.0f, 0.0001));
        REQUIRE_THAT(d2d_red.g, Catch::Matchers::WithinAbs(0.0f, 0.0001));
        REQUIRE_THAT(d2d_red.b, Catch::Matchers::WithinAbs(0.0f, 0.0001));
        REQUIRE_THAT(d2d_red.a, Catch::Matchers::WithinAbs(1.0f, 0.0001));
    }

    SECTION("Half values") {
        color_t gray(128, 128, 128, 128);
        auto d2d_gray = gray.to_direct2d();
        REQUIRE_THAT(d2d_gray.r, Catch::Matchers::WithinAbs(128.0f / 255.0f, 0.0001));
        REQUIRE_THAT(d2d_gray.g, Catch::Matchers::WithinAbs(128.0f / 255.0f, 0.0001));
        REQUIRE_THAT(d2d_gray.b, Catch::Matchers::WithinAbs(128.0f / 255.0f, 0.0001));
        REQUIRE_THAT(d2d_gray.a, Catch::Matchers::WithinAbs(128.0f / 255.0f, 0.0001));
    }

    SECTION("Black and transparent") {
        color_t black(0, 0, 0, 0);
        auto d2d_black = black.to_direct2d();
        REQUIRE_THAT(d2d_black.r, Catch::Matchers::WithinAbs(0.0f, 0.0001));
        REQUIRE_THAT(d2d_black.g, Catch::Matchers::WithinAbs(0.0f, 0.0001));
        REQUIRE_THAT(d2d_black.b, Catch::Matchers::WithinAbs(0.0f, 0.0001));
        REQUIRE_THAT(d2d_black.a, Catch::Matchers::WithinAbs(0.0f, 0.0001));
    }

    SECTION("Mixed values") {
        color_t color(64, 192, 32, 224);
        auto d2d_color = color.to_direct2d();
        REQUIRE_THAT(d2d_color.r, Catch::Matchers::WithinAbs(64.0f / 255.0f, 0.0001));
        REQUIRE_THAT(d2d_color.g, Catch::Matchers::WithinAbs(192.0f / 255.0f, 0.0001));
        REQUIRE_THAT(d2d_color.b, Catch::Matchers::WithinAbs(32.0f / 255.0f, 0.0001));
        REQUIRE_THAT(d2d_color.a, Catch::Matchers::WithinAbs(224.0f / 255.0f, 0.0001));
    }
}

TEST_CASE("Predefined colors", "[color_t][predefined]") {
    using namespace colors;

    SECTION("Red color") {
        REQUIRE(red.r == 255);
        REQUIRE(red.g == 0);
        REQUIRE(red.b == 0);
        REQUIRE(red.a == 255);
    }

    SECTION("Green color") {
        REQUIRE(green.r == 0);
        REQUIRE(green.g == 255);
        REQUIRE(green.b == 0);
        REQUIRE(green.a == 255);
    }

    SECTION("Blue color") {
        REQUIRE(blue.r == 0);
        REQUIRE(blue.g == 0);
        REQUIRE(blue.b == 255);
        REQUIRE(blue.a == 255);
    }

    SECTION("Black color") {
        REQUIRE(black.r == 0);
        REQUIRE(black.g == 0);
        REQUIRE(black.b == 0);
        REQUIRE(black.a == 255);
    }

    SECTION("White color") {
        REQUIRE(white.r == 255);
        REQUIRE(white.g == 255);
        REQUIRE(white.b == 255);
        REQUIRE(white.a == 255);
    }

    SECTION("Predefined colors hex conversion") {
        REQUIRE(red.to_hex() == 0xFF0000FF);
        REQUIRE(green.to_hex() == 0x00FF00FF);
        REQUIRE(blue.to_hex() == 0x0000FFFF);
        REQUIRE(black.to_hex() == 0x000000FF);
        REQUIRE(white.to_hex() == 0xFFFFFFFF);
    }
}

// vec2_t
//

TEST_CASE("vec2_t default constructor", "[vec2_t][constructor]") {
    vec2_t<float> v;
    REQUIRE(v.x == 0.0f);
    REQUIRE(v.y == 0.0f);
}

TEST_CASE("vec2_t two-parameter constructor", "[vec2_t][constructor]") {
    vec2_t<float> v(3.0f, 4.0f);
    REQUIRE(v.x == 3.0f);
    REQUIRE(v.y == 4.0f);
}

TEST_CASE("vec2_t single-parameter constructor", "[vec2_t][constructor]") {
    vec2_t<float> v(5.0f);
    REQUIRE(v.x == 5.0f);
    REQUIRE(v.y == 5.0f);
}

TEST_CASE("vec2_t with integer types", "[vec2_t][types]") {
    SECTION("int type") {
        vec2_t<int> v(10, 20);
        REQUIRE(v.x == 10);
        REQUIRE(v.y == 20);
    }

    SECTION("double type") {
        vec2_t<double> v(1.5, 2.5);
        REQUIRE(v.x == 1.5);
        REQUIRE(v.y == 2.5);
    }
}

TEST_CASE("vec2_t addition operator", "[vec2_t][operators]") {
    vec2_t<float> v1(1.0f, 2.0f);
    vec2_t<float> v2(3.0f, 4.0f);

    vec2_t<float> result = v1 + v2;
    REQUIRE(result.x == 4.0f);
    REQUIRE(result.y == 6.0f);

    // Test that original vectors are unchanged
    REQUIRE(v1.x == 1.0f);
    REQUIRE(v1.y == 2.0f);
}

TEST_CASE("vec2_t subtraction operator", "[vec2_t][operators]") {
    vec2_t<float> v1(5.0f, 7.0f);
    vec2_t<float> v2(2.0f, 3.0f);

    vec2_t<float> result = v1 - v2;
    REQUIRE(result.x == 3.0f);
    REQUIRE(result.y == 4.0f);
}

TEST_CASE("vec2_t multiplication operators", "[vec2_t][operators]") {
    SECTION("vector multiplication") {
        vec2_t<float> v1(2.0f, 3.0f);
        vec2_t<float> v2(4.0f, 5.0f);

        vec2_t<float> result = v1 * v2;
        REQUIRE(result.x == 8.0f);
        REQUIRE(result.y == 15.0f);
    }

    SECTION("scalar multiplication") {
        vec2_t<float> v(2.0f, 3.0f);
        float scalar = 2.5f;

        vec2_t<float> result = v * scalar;
        REQUIRE_THAT(result.x, Catch::Matchers::WithinAbs(5.0f, 0.0001));
        REQUIRE_THAT(result.y, Catch::Matchers::WithinAbs(7.5f, 0.0001));
    }
}

TEST_CASE("vec2_t division operators", "[vec2_t][operators]") {
    SECTION("vector division") {
        vec2_t<float> v1(8.0f, 15.0f);
        vec2_t<float> v2(2.0f, 3.0f);

        vec2_t<float> result = v1 / v2;
        REQUIRE(result.x == 4.0f);
        REQUIRE(result.y == 5.0f);
    }

    SECTION("scalar division") {
        vec2_t<float> v(10.0f, 15.0f);
        float scalar = 2.0f;

        vec2_t<float> result = v / scalar;
        REQUIRE(result.x == 5.0f);
        REQUIRE(result.y == 7.5f);
    }
}

TEST_CASE("vec2_t compound assignment operators", "[vec2_t][operators]") {
    SECTION("addition assignment") {
        vec2_t<float> v1(1.0f, 2.0f);
        vec2_t<float> v2(3.0f, 4.0f);

        vec2_t<float>& result = v1 += v2;
        REQUIRE(v1.x == 4.0f);
        REQUIRE(v1.y == 6.0f);
        REQUIRE(&result == &v1); // Check return reference
    }

    SECTION("subtraction assignment") {
        vec2_t<float> v1(5.0f, 7.0f);
        vec2_t<float> v2(2.0f, 3.0f);

        v1 -= v2;
        REQUIRE(v1.x == 3.0f);
        REQUIRE(v1.y == 4.0f);
    }

    SECTION("multiplication assignment") {
        vec2_t<float> v1(2.0f, 3.0f);
        vec2_t<float> v2(4.0f, 5.0f);

        v1 *= v2;
        REQUIRE(v1.x == 8.0f);
        REQUIRE(v1.y == 15.0f);
    }

    SECTION("division assignment") {
        vec2_t<float> v1(8.0f, 15.0f);
        vec2_t<float> v2(2.0f, 3.0f);

        v1 /= v2;
        REQUIRE(v1.x == 4.0f);
        REQUIRE(v1.y == 5.0f);
    }
}

TEST_CASE("vec2_t is_zero method", "[vec2_t][methods]") {
    SECTION("zero vector") {
        vec2_t<float> v(0.0f, 0.0f);
        REQUIRE(v.is_zero());

        vec2_t<int> vi(0, 0);
        REQUIRE(vi.is_zero());
    }

    SECTION("non-zero vector") {
        vec2_t<float> v1(1.0f, 0.0f);
        REQUIRE_FALSE(v1.is_zero());

        vec2_t<float> v2(0.0f, 1.0f);
        REQUIRE_FALSE(v2.is_zero());

        vec2_t<float> v3(1.0f, 1.0f);
        REQUIRE_FALSE(v3.is_zero());
    }

    SECTION("default constructed vector") {
        vec2_t<float> v;
        REQUIRE(v.is_zero());
    }
}

TEST_CASE("vec2_t is_valid method", "[vec2_t][methods]") {
    SECTION("valid vectors") {
        vec2_t<float> v1(1.0f, 2.0f);
        REQUIRE(v1.is_valid());

        vec2_t<float> v2(0.0f, 0.0f);
        REQUIRE(v2.is_valid());

        vec2_t<float> v3(-1.0f, -2.0f);
        REQUIRE(v3.is_valid());
    }

    SECTION("invalid vectors with infinity") {
        vec2_t<float> v1(std::numeric_limits<float>::infinity(), 1.0f);
        REQUIRE_FALSE(v1.is_valid());

        vec2_t<float> v2(1.0f, std::numeric_limits<float>::infinity());
        REQUIRE_FALSE(v2.is_valid());

        vec2_t<float> v3(std::numeric_limits<float>::infinity(), std::numeric_limits<float>::infinity());
        REQUIRE_FALSE(v3.is_valid());
    }

    SECTION("invalid vectors with NaN") {
        vec2_t<float> v1(std::numeric_limits<float>::quiet_NaN(), 1.0f);
        REQUIRE_FALSE(v1.is_valid());

        vec2_t<float> v2(1.0f, std::numeric_limits<float>::quiet_NaN());
        REQUIRE_FALSE(v2.is_valid());
    }
}

TEST_CASE("vec2_t magnitude method", "[vec2_t][methods]") {
    SECTION("basic magnitude calculations") {
        vec2_t<float> v1(3.0f, 4.0f);
        REQUIRE_THAT(v1.magnitude(), Catch::Matchers::WithinAbs(5.0f, 0.0001));

        vec2_t<float> v2(0.0f, 0.0f);
        REQUIRE_THAT(v2.magnitude(), Catch::Matchers::WithinAbs(0.0f, 0.0001));

        vec2_t<float> v3(1.0f, 0.0f);
        REQUIRE_THAT(v3.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001));

        vec2_t<float> v4(0.0f, 1.0f);
        REQUIRE_THAT(v4.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001));
    }

    SECTION("negative components") {
        vec2_t<float> v1(-3.0f, -4.0f);
        REQUIRE_THAT(v1.magnitude(), Catch::Matchers::WithinAbs(5.0f, 0.0001));

        vec2_t<float> v2(-3.0f, 4.0f);
        REQUIRE_THAT(v2.magnitude(), Catch::Matchers::WithinAbs(5.0f, 0.0001));
    }

    SECTION("integer type") {
        vec2_t<int> v(3, 4);
        REQUIRE_THAT(v.magnitude(), Catch::Matchers::WithinAbs(5.0f, 0.0001));
    }
}

TEST_CASE("vec2_t magnitude_squared method", "[vec2_t][methods]") {
    SECTION("basic magnitude squared calculations") {
        vec2_t<float> v1(3.0f, 4.0f);
        REQUIRE(v1.magnitude_squared() == 25.0f);

        vec2_t<float> v2(0.0f, 0.0f);
        REQUIRE(v2.magnitude_squared() == 0.0f);

        vec2_t<float> v3(2.0f, 2.0f);
        REQUIRE(v3.magnitude_squared() == 8.0f);
    }

    SECTION("negative components") {
        vec2_t<float> v1(-3.0f, -4.0f);
        REQUIRE(v1.magnitude_squared() == 25.0f);
    }

    SECTION("consistency with magnitude") {
        vec2_t<float> v(5.0f, 12.0f);
        float mag = v.magnitude();
        float mag_sq = v.magnitude_squared();
        REQUIRE_THAT(mag_sq, Catch::Matchers::WithinAbs(mag * mag, 0.0001));
    }
}

TEST_CASE("vec2_t distance_to method", "[vec2_t][methods]") {
    SECTION("basic distance calculations") {
        vec2_t<float> v1(0.0f, 0.0f);
        vec2_t<float> v2(3.0f, 4.0f);

        REQUIRE_THAT(v1.distance_to(v2), Catch::Matchers::WithinAbs(5.0f, 0.0001));
        REQUIRE_THAT(v2.distance_to(v1), Catch::Matchers::WithinAbs(5.0f, 0.0001));
    }

    SECTION("distance to self") {
        vec2_t<float> v(1.0f, 2.0f);
        REQUIRE_THAT(v.distance_to(v), Catch::Matchers::WithinAbs(0.0f, 0.0001));
    }

    SECTION("horizontal and vertical distances") {
        vec2_t<float> v1(0.0f, 0.0f);
        vec2_t<float> v2(5.0f, 0.0f);
        vec2_t<float> v3(0.0f, 5.0f);

        REQUIRE_THAT(v1.distance_to(v2), Catch::Matchers::WithinAbs(5.0f, 0.0001));
        REQUIRE_THAT(v1.distance_to(v3), Catch::Matchers::WithinAbs(5.0f, 0.0001));
    }

    SECTION("negative coordinates") {
        vec2_t<float> v1(-1.0f, -1.0f);
        vec2_t<float> v2(2.0f, 3.0f);

        float expected = std::sqrt(9.0f + 16.0f); // sqrt((2-(-1))^2 + (3-(-1))^2)
        REQUIRE_THAT(v1.distance_to(v2), Catch::Matchers::WithinAbs(expected, 0.0001));
    }
}

TEST_CASE("vec2_t edge cases", "[vec2_t][edge_cases]") {
    SECTION("very small numbers") {
        vec2_t<float> v(1e-10f, 1e-10f);
        REQUIRE_FALSE(v.is_zero());
        REQUIRE(v.is_valid());
        REQUIRE(v.magnitude() > 0.0f);
    }

    SECTION("very large numbers") {
        vec2_t<float> v(1e10f, 1e10f);
        REQUIRE(v.is_valid());
        REQUIRE(v.magnitude() > 0.0f);
    }

    SECTION("mixed positive and negative") {
        vec2_t<float> v1(5.0f, -3.0f);
        vec2_t<float> v2(-2.0f, 4.0f);

        vec2_t<float> sum = v1 + v2;
        REQUIRE(sum.x == 3.0f);
        REQUIRE(sum.y == 1.0f);
    }
}

TEST_CASE("vec2_t operator chaining", "[vec2_t][chaining]") {
    vec2_t<float> v1(1.0f, 2.0f);
    vec2_t<float> v2(3.0f, 4.0f);
    vec2_t<float> v3(2.0f, 2.0f);

    // Test chaining compound assignments
    v1 += v2 += v3;
    REQUIRE(v2.x == 5.0f);
    REQUIRE(v2.y == 6.0f);
    REQUIRE(v1.x == 6.0f);
    REQUIRE(v1.y == 8.0f);
}

TEST_CASE("vec2_t type deduction", "[vec2_t][template]") {
    // Test default template parameter
    vec2_t<> v1; // Should default to float
    REQUIRE(std::is_same_v<decltype(v1.x), float>);

    // Test explicit types
    vec2_t<double> v2;
    REQUIRE(std::is_same_v<decltype(v2.x), double>);

    vec2_t<int> v3;
    REQUIRE(std::is_same_v<decltype(v3.x), int>);
}

// vec3_t
//

TEST_CASE("vec3_t default constructor", "[vec3_t][constructor]") {
    vec3_t<float> v;
    REQUIRE(v.x == 0.0f);
    REQUIRE(v.y == 0.0f);
    REQUIRE(v.z == 0.0f);
}

TEST_CASE("vec3_t three-parameter constructor", "[vec3_t][constructor]") {
    vec3_t<float> v(1.0f, 2.0f, 3.0f);
    REQUIRE(v.x == 1.0f);
    REQUIRE(v.y == 2.0f);
    REQUIRE(v.z == 3.0f);
}

TEST_CASE("vec3_t single-parameter constructor", "[vec3_t][constructor]") {
    vec3_t<float> v(5.0f);
    REQUIRE(v.x == 5.0f);
    REQUIRE(v.y == 5.0f);
    REQUIRE(v.z == 5.0f);
}

TEST_CASE("vec3_t with different types", "[vec3_t][types]") {
    SECTION("int type") {
        vec3_t<int> v(10, 20, 30);
        REQUIRE(v.x == 10);
        REQUIRE(v.y == 20);
        REQUIRE(v.z == 30);
    }

    SECTION("double type") {
        vec3_t<double> v(1.5, 2.5, 3.5);
        REQUIRE(v.x == 1.5);
        REQUIRE(v.y == 2.5);
        REQUIRE(v.z == 3.5);
    }
}

TEST_CASE("vec3_t addition operator", "[vec3_t][operators]") {
    vec3_t<float> v1(1.0f, 2.0f, 3.0f);
    vec3_t<float> v2(4.0f, 5.0f, 6.0f);

    vec3_t<float> result = v1 + v2;
    REQUIRE(result.x == 5.0f);
    REQUIRE(result.y == 7.0f);
    REQUIRE(result.z == 9.0f);

    // Test that original vectors are unchanged
    REQUIRE(v1.x == 1.0f);
    REQUIRE(v1.y == 2.0f);
    REQUIRE(v1.z == 3.0f);
}

TEST_CASE("vec3_t subtraction operator", "[vec3_t][operators]") {
    vec3_t<float> v1(7.0f, 8.0f, 9.0f);
    vec3_t<float> v2(2.0f, 3.0f, 4.0f);

    vec3_t<float> result = v1 - v2;
    REQUIRE(result.x == 5.0f);
    REQUIRE(result.y == 5.0f);
    REQUIRE(result.z == 5.0f);
}

TEST_CASE("vec3_t multiplication operators", "[vec3_t][operators]") {
    SECTION("vector multiplication") {
        vec3_t<float> v1(2.0f, 3.0f, 4.0f);
        vec3_t<float> v2(5.0f, 6.0f, 7.0f);

        vec3_t<float> result = v1 * v2;
        REQUIRE(result.x == 10.0f);
        REQUIRE(result.y == 18.0f);
        REQUIRE(result.z == 28.0f);
    }

    SECTION("scalar multiplication") {
        vec3_t<float> v(2.0f, 3.0f, 4.0f);
        float scalar = 2.5f;

        vec3_t<float> result = v * scalar;
        REQUIRE_THAT(result.x, Catch::Matchers::WithinAbs(5.0f, 0.0001f));
        REQUIRE_THAT(result.y, Catch::Matchers::WithinAbs(7.5f, 0.0001f));
        REQUIRE_THAT(result.z, Catch::Matchers::WithinAbs(10.0f, 0.0001f));
    }
}

TEST_CASE("vec3_t division operators", "[vec3_t][operators]") {
    SECTION("vector division") {
        vec3_t<float> v1(10.0f, 18.0f, 28.0f);
        vec3_t<float> v2(2.0f, 3.0f, 4.0f);

        vec3_t<float> result = v1 / v2;
        REQUIRE(result.x == 5.0f);
        REQUIRE(result.y == 6.0f);
        REQUIRE(result.z == 7.0f);
    }

    SECTION("scalar division") {
        vec3_t<float> v(10.0f, 15.0f, 20.0f);
        float scalar = 2.0f;

        vec3_t<float> result = v / scalar;
        REQUIRE(result.x == 5.0f);
        REQUIRE_THAT(result.y, Catch::Matchers::WithinAbs(7.5f, 0.0001f));
        REQUIRE(result.z == 10.0f);
    }
}

TEST_CASE("vec3_t compound assignment operators", "[vec3_t][operators]") {
    SECTION("addition assignment") {
        vec3_t<float> v1(1.0f, 2.0f, 3.0f);
        vec3_t<float> v2(4.0f, 5.0f, 6.0f);

        vec3_t<float>& result = v1 += v2;
        REQUIRE(v1.x == 5.0f);
        REQUIRE(v1.y == 7.0f);
        REQUIRE(v1.z == 9.0f);
        REQUIRE(&result == &v1); // Check return reference
    }

    SECTION("subtraction assignment") {
        vec3_t<float> v1(7.0f, 8.0f, 9.0f);
        vec3_t<float> v2(2.0f, 3.0f, 4.0f);

        v1 -= v2;
        REQUIRE(v1.x == 5.0f);
        REQUIRE(v1.y == 5.0f);
        REQUIRE(v1.z == 5.0f);
    }

    SECTION("multiplication assignment") {
        vec3_t<float> v1(2.0f, 3.0f, 4.0f);
        vec3_t<float> v2(5.0f, 6.0f, 7.0f);

        v1 *= v2;
        REQUIRE(v1.x == 10.0f);
        REQUIRE(v1.y == 18.0f);
        REQUIRE(v1.z == 28.0f);
    }

    SECTION("division assignment") {
        vec3_t<float> v1(10.0f, 18.0f, 28.0f);
        vec3_t<float> v2(2.0f, 3.0f, 4.0f);

        v1 /= v2;
        REQUIRE(v1.x == 5.0f);
        REQUIRE(v1.y == 6.0f);
        REQUIRE(v1.z == 7.0f);
    }
}

TEST_CASE("vec3_t is_zero method", "[vec3_t][methods]") {
    SECTION("zero vector") {
        vec3_t<float> v(0.0f, 0.0f, 0.0f);
        REQUIRE(v.is_zero());

        vec3_t<int> vi(0, 0, 0);
        REQUIRE(vi.is_zero());
    }

    SECTION("non-zero vector") {
        vec3_t<float> v1(1.0f, 0.0f, 0.0f);
        REQUIRE_FALSE(v1.is_zero());

        vec3_t<float> v2(0.0f, 1.0f, 0.0f);
        REQUIRE_FALSE(v2.is_zero());

        vec3_t<float> v3(0.0f, 0.0f, 1.0f);
        REQUIRE_FALSE(v3.is_zero());

        vec3_t<float> v4(1.0f, 1.0f, 1.0f);
        REQUIRE_FALSE(v4.is_zero());
    }

    SECTION("default constructed vector") {
        vec3_t<float> v;
        REQUIRE(v.is_zero());
    }
}

TEST_CASE("vec3_t is_valid method", "[vec3_t][methods]") {
    SECTION("valid vectors") {
        vec3_t<float> v1(1.0f, 2.0f, 3.0f);
        REQUIRE(v1.is_valid());

        vec3_t<float> v2(0.0f, 0.0f, 0.0f);
        REQUIRE(v2.is_valid());

        vec3_t<float> v3(-1.0f, -2.0f, -3.0f);
        REQUIRE(v3.is_valid());
    }

    SECTION("invalid vectors with infinity") {
        vec3_t<float> v1(std::numeric_limits<float>::infinity(), 1.0f, 1.0f);
        REQUIRE_FALSE(v1.is_valid());

        vec3_t<float> v2(1.0f, std::numeric_limits<float>::infinity(), 1.0f);
        REQUIRE_FALSE(v2.is_valid());

        vec3_t<float> v3(1.0f, 1.0f, std::numeric_limits<float>::infinity());
        REQUIRE_FALSE(v3.is_valid());
    }

    SECTION("invalid vectors with NaN") {
        vec3_t<float> v1(std::numeric_limits<float>::quiet_NaN(), 1.0f, 1.0f);
        REQUIRE_FALSE(v1.is_valid());

        vec3_t<float> v2(1.0f, std::numeric_limits<float>::quiet_NaN(), 1.0f);
        REQUIRE_FALSE(v2.is_valid());

        vec3_t<float> v3(1.0f, 1.0f, std::numeric_limits<float>::quiet_NaN());
        REQUIRE_FALSE(v3.is_valid());
    }
}

TEST_CASE("vec3_t magnitude method", "[vec3_t][methods]") {
    SECTION("basic magnitude calculations") {
        vec3_t<float> v1(0.0f, 0.0f, 0.0f);
        REQUIRE_THAT(v1.magnitude(), Catch::Matchers::WithinAbs(0.0f, 0.0001f));

        vec3_t<float> v2(1.0f, 0.0f, 0.0f);
        REQUIRE_THAT(v2.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));

        vec3_t<float> v3(0.0f, 1.0f, 0.0f);
        REQUIRE_THAT(v3.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));

        vec3_t<float> v4(0.0f, 0.0f, 1.0f);
        REQUIRE_THAT(v4.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));

        vec3_t<float> v5(1.0f, 1.0f, 1.0f);
        REQUIRE_THAT(v5.magnitude(), Catch::Matchers::WithinAbs(std::sqrt(3.0f), 0.0001f));
    }

    SECTION("pythagorean triple") {
        vec3_t<float> v(2.0f, 3.0f, 6.0f);
        REQUIRE_THAT(v.magnitude(), Catch::Matchers::WithinAbs(7.0f, 0.0001f));
    }

    SECTION("negative components") {
        vec3_t<float> v1(-2.0f, -3.0f, -6.0f);
        REQUIRE_THAT(v1.magnitude(), Catch::Matchers::WithinAbs(7.0f, 0.0001f));

        vec3_t<float> v2(-1.0f, 2.0f, -3.0f);
        REQUIRE_THAT(v2.magnitude(), Catch::Matchers::WithinAbs(std::sqrt(14.0f), 0.0001f));
    }

    SECTION("integer type") {
        vec3_t<int> v(2, 3, 6);
        REQUIRE_THAT(v.magnitude(), Catch::Matchers::WithinAbs(7.0, 0.0001));
    }
}

TEST_CASE("vec3_t magnitude_squared method", "[vec3_t][methods]") {
    SECTION("basic magnitude squared calculations") {
        vec3_t<float> v1(0.0f, 0.0f, 0.0f);
        REQUIRE(v1.magnitude_squared() == 0.0f);

        vec3_t<float> v2(1.0f, 2.0f, 3.0f);
        REQUIRE(v2.magnitude_squared() == 14.0f);

        vec3_t<float> v3(2.0f, 3.0f, 6.0f);
        REQUIRE(v3.magnitude_squared() == 49.0f);
    }

    SECTION("negative components") {
        vec3_t<float> v1(-2.0f, -3.0f, -6.0f);
        REQUIRE(v1.magnitude_squared() == 49.0f);
    }

    SECTION("consistency with magnitude") {
        vec3_t<float> v(3.0f, 4.0f, 5.0f);
        float mag = v.magnitude();
        float mag_sq = v.magnitude_squared();
        REQUIRE_THAT(mag_sq, Catch::Matchers::WithinAbs(mag * mag, 0.0001f));
    }
}

TEST_CASE("vec3_t dot_product method", "[vec3_t][methods]") {
    SECTION("basic dot product calculations") {
        vec3_t<float> v1(1.0f, 2.0f, 3.0f);
        vec3_t<float> v2(4.0f, 5.0f, 6.0f);

        float dot = v1.dot_product(v2);
        REQUIRE(dot == 32.0f); // 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32
    }

    SECTION("dot product with self") {
        vec3_t<float> v(2.0f, 3.0f, 4.0f);
        float dot = v.dot_product(v);
        REQUIRE(dot == v.magnitude_squared());
    }

    SECTION("orthogonal vectors") {
        vec3_t<float> v1(1.0f, 0.0f, 0.0f);
        vec3_t<float> v2(0.0f, 1.0f, 0.0f);

        REQUIRE(v1.dot_product(v2) == 0.0f);
        REQUIRE(v2.dot_product(v1) == 0.0f);
    }

    SECTION("negative components") {
        vec3_t<float> v1(-1.0f, 2.0f, -3.0f);
        vec3_t<float> v2(4.0f, -5.0f, 6.0f);

        float dot = v1.dot_product(v2);
        REQUIRE(dot == -32.0f); // -1*4 + 2*(-5) + (-3)*6 = -4 - 10 - 18 = -32
    }
}

TEST_CASE("vec3_t cross_product method", "[vec3_t][methods]") {
    SECTION("basic cross product calculations") {
        vec3_t<float> v1(1.0f, 0.0f, 0.0f);
        vec3_t<float> v2(0.0f, 1.0f, 0.0f);

        vec3_t<float> cross = v1.cross_product(v2);
        REQUIRE(cross.x == 0.0f);
        REQUIRE(cross.y == 0.0f);
        REQUIRE(cross.z == 1.0f);
    }

    SECTION("reverse order gives negative") {
        vec3_t<float> v1(1.0f, 0.0f, 0.0f);
        vec3_t<float> v2(0.0f, 1.0f, 0.0f);

        vec3_t<float> cross1 = v1.cross_product(v2);
        vec3_t<float> cross2 = v2.cross_product(v1);

        REQUIRE(cross1.x == -cross2.x);
        REQUIRE(cross1.y == -cross2.y);
        REQUIRE(cross1.z == -cross2.z);
    }

    SECTION("cross product with self is zero") {
        vec3_t<float> v(1.0f, 2.0f, 3.0f);
        vec3_t<float> cross = v.cross_product(v);

        REQUIRE(cross.x == 0.0f);
        REQUIRE(cross.y == 0.0f);
        REQUIRE(cross.z == 0.0f);
    }

    SECTION("general cross product") {
        vec3_t<float> v1(2.0f, 3.0f, 4.0f);
        vec3_t<float> v2(5.0f, 6.0f, 7.0f);

        vec3_t<float> cross = v1.cross_product(v2);
        // Expected: (3*7 - 4*6, 4*5 - 2*7, 2*6 - 3*5) = (-3, 6, -3)
        REQUIRE(cross.x == -3.0f);
        REQUIRE(cross.y == 6.0f);
        REQUIRE(cross.z == -3.0f);
    }

    SECTION("cross product orthogonality") {
        vec3_t<float> v1(1.0f, 2.0f, 3.0f);
        vec3_t<float> v2(4.0f, 5.0f, 6.0f);
        vec3_t<float> cross = v1.cross_product(v2);

        // Cross product should be orthogonal to both input vectors
        REQUIRE_THAT(v1.dot_product(cross), Catch::Matchers::WithinAbs(0.0f, 0.0001f));
        REQUIRE_THAT(v2.dot_product(cross), Catch::Matchers::WithinAbs(0.0f, 0.0001f));
    }
}

TEST_CASE("vec3_t distance_to method", "[vec3_t][methods]") {
    SECTION("basic distance calculations") {
        vec3_t<float> v1(0.0f, 0.0f, 0.0f);
        vec3_t<float> v2(1.0f, 2.0f, 3.0f);

        float expected = std::sqrt(14.0f);
        REQUIRE_THAT(v1.distance_to(v2), Catch::Matchers::WithinAbs(expected, 0.0001f));
        REQUIRE_THAT(v2.distance_to(v1), Catch::Matchers::WithinAbs(expected, 0.0001f)); // Distance is symmetric
    }

    SECTION("distance to self") {
        vec3_t<float> v(1.0f, 2.0f, 3.0f);
        REQUIRE_THAT(v.distance_to(v), Catch::Matchers::WithinAbs(0.0f, 0.0001f));
    }

    SECTION("axis-aligned distances") {
        vec3_t<float> v1(0.0f, 0.0f, 0.0f);
        vec3_t<float> v2(5.0f, 0.0f, 0.0f);
        vec3_t<float> v3(0.0f, 5.0f, 0.0f);
        vec3_t<float> v4(0.0f, 0.0f, 5.0f);

        REQUIRE_THAT(v1.distance_to(v2), Catch::Matchers::WithinAbs(5.0f, 0.0001f));
        REQUIRE_THAT(v1.distance_to(v3), Catch::Matchers::WithinAbs(5.0f, 0.0001f));
        REQUIRE_THAT(v1.distance_to(v4), Catch::Matchers::WithinAbs(5.0f, 0.0001f));
    }

    SECTION("negative coordinates") {
        vec3_t<float> v1(-1.0f, -2.0f, -3.0f);
        vec3_t<float> v2(2.0f, 3.0f, 4.0f);

        float expected = std::sqrt(9.0f + 25.0f + 49.0f); // sqrt(3^2 + 5^2 + 7^2)
        REQUIRE_THAT(v1.distance_to(v2), Catch::Matchers::WithinAbs(expected, 0.0001f));
    }
}

TEST_CASE("vec3_t normalized method", "[vec3_t][methods]") {
    SECTION("normalize unit vectors") {
        vec3_t<float> v1(1.0f, 0.0f, 0.0f);
        vec3_t<float> norm1 = v1.normalized();

        REQUIRE_THAT(norm1.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(norm1.x, Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(norm1.y, Catch::Matchers::WithinAbs(0.0f, 0.0001f));
        REQUIRE_THAT(norm1.z, Catch::Matchers::WithinAbs(0.0f, 0.0001f));
    }

    SECTION("normalize general vector") {
        vec3_t<float> v(3.0f, 4.0f, 0.0f);
        vec3_t<float> norm = v.normalized();

        REQUIRE_THAT(norm.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(norm.x, Catch::Matchers::WithinAbs(0.6f, 0.0001f));
        REQUIRE_THAT(norm.y, Catch::Matchers::WithinAbs(0.8f, 0.0001f));
        REQUIRE_THAT(norm.z, Catch::Matchers::WithinAbs(0.0f, 0.0001f));
    }

    SECTION("original vector unchanged") {
        vec3_t<float> v(2.0f, 3.0f, 6.0f);
        vec3_t<float> original = v;
        vec3_t<float> norm = v.normalized();
        (void)norm;

        REQUIRE(v.x == original.x);
        REQUIRE(v.y == original.y);
        REQUIRE(v.z == original.z);
    }
}

TEST_CASE("vec3_t normalize method", "[vec3_t][methods]") {
    SECTION("normalize unit vectors") {
        vec3_t<float> v(1.0f, 0.0f, 0.0f);
        vec3_t<float>& result = v.normalize();

        REQUIRE_THAT(v.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(v.x, Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(v.y, Catch::Matchers::WithinAbs(0.0f, 0.0001f));
        REQUIRE_THAT(v.z, Catch::Matchers::WithinAbs(0.0f, 0.0001f));
        REQUIRE(&result == &v); // Check return reference
    }

    SECTION("normalize general vector") {
        vec3_t<float> v(3.0f, 4.0f, 0.0f);
        v.normalize();

        REQUIRE_THAT(v.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(v.x, Catch::Matchers::WithinAbs(0.6f, 0.0001f));
        REQUIRE_THAT(v.y, Catch::Matchers::WithinAbs(0.8f, 0.0001f));
        REQUIRE_THAT(v.z, Catch::Matchers::WithinAbs(0.0f, 0.0001f));
    }

    SECTION("normalize 3D vector") {
        vec3_t<float> v(1.0f, 1.0f, 1.0f);
        v.normalize();

        float expected = 1.0f / std::sqrt(3.0f);
        REQUIRE_THAT(v.magnitude(), Catch::Matchers::WithinAbs(1.0f, 0.0001f));
        REQUIRE_THAT(v.x, Catch::Matchers::WithinAbs(expected, 0.0001f));
        REQUIRE_THAT(v.y, Catch::Matchers::WithinAbs(expected, 0.0001f));
        REQUIRE_THAT(v.z, Catch::Matchers::WithinAbs(expected, 0.0001f));
    }
}

TEST_CASE("vec3_t edge cases", "[vec3_t][edge_cases]") {
    SECTION("very small numbers") {
        vec3_t<float> v(1e-10f, 1e-10f, 1e-10f);
        REQUIRE_FALSE(v.is_zero());
        REQUIRE(v.is_valid());
        REQUIRE(v.magnitude() > 0.0f);
    }

    SECTION("very large numbers") {
        vec3_t<float> v(1e10f, 1e10f, 1e10f);
        REQUIRE(v.is_valid());
        REQUIRE(v.magnitude() > 0.0f);
    }

    SECTION("mixed positive and negative") {
        vec3_t<float> v1(5.0f, -3.0f, 2.0f);
        vec3_t<float> v2(-2.0f, 4.0f, -1.0f);

        vec3_t<float> sum = v1 + v2;
        REQUIRE(sum.x == 3.0f);
        REQUIRE(sum.y == 1.0f);
        REQUIRE(sum.z == 1.0f);
    }
}

TEST_CASE("vec3_t operator chaining", "[vec3_t][chaining]") {
    vec3_t<float> v1(1.0f, 2.0f, 3.0f);
    vec3_t<float> v2(4.0f, 5.0f, 6.0f);
    vec3_t<float> v3(2.0f, 2.0f, 2.0f);

    // Test chaining compound assignments
    v1 += v2 += v3;
    REQUIRE(v2.x == 6.0f);
    REQUIRE(v2.y == 7.0f);
    REQUIRE(v2.z == 8.0f);
    REQUIRE(v1.x == 7.0f);
    REQUIRE(v1.y == 9.0f);
    REQUIRE(v1.z == 11.0f);
}

TEST_CASE("vec3_t type deduction", "[vec3_t][template]") {
    // Test default template parameter
    vec3_t<> v1; // Should default to float
    REQUIRE(std::is_same_v<decltype(v1.x), float>);

    // Test explicit types
    vec3_t<double> v2;
    REQUIRE(std::is_same_v<decltype(v2.x), double>);

    vec3_t<int> v3;
    REQUIRE(std::is_same_v<decltype(v3.x), int>);
}

TEST_CASE("vec3_t mathematical properties", "[vec3_t][properties]") {
    SECTION("cross product magnitude") {
        vec3_t<float> v1(1.0f, 0.0f, 0.0f);
        vec3_t<float> v2(0.0f, 1.0f, 0.0f);
        vec3_t<float> cross = v1.cross_product(v2);

        // |a × b| = |a| * |b| * sin(θ) - for perpendicular vectors, sin(90°) = 1
        float expected_magnitude = v1.magnitude() * v2.magnitude();
        REQUIRE_THAT(cross.magnitude(), Catch::Matchers::WithinAbs(expected_magnitude, 0.0001f));
    }

    SECTION("dot product properties") {
        vec3_t<float> v1(1.0f, 2.0f, 3.0f);
        vec3_t<float> v2(4.0f, 5.0f, 6.0f);

        // Commutative property: a · b = b · a
        REQUIRE(v1.dot_product(v2) == v2.dot_product(v1));

        // Distributive property: a · (b + c) = a · b + a · c
        vec3_t<float> v3(1.0f, 1.0f, 1.0f);
        vec3_t<float> sum = v2 + v3;
        float left = v1.dot_product(sum);
        float right = v1.dot_product(v2) + v1.dot_product(v3);
        REQUIRE_THAT(left, Catch::Matchers::WithinAbs(right, 0.0001f));
    }

    SECTION("normalization preserves direction") {
        vec3_t<float> v(3.0f, 4.0f, 5.0f);
        vec3_t<float> norm = v.normalized();

        // Normalized vector should be parallel (dot product / magnitudes = 1)
        float dot = v.dot_product(norm);
        float expected = v.magnitude() * norm.magnitude();
        REQUIRE_THAT(dot, Catch::Matchers::WithinAbs(expected, 0.0001f));
    }
}
